name: dat_filter
environment:
    sdk: '>=3.6.0 <5.0.0'
publish_to: none
workspace:
    - packages/app
    - packages/artistic
    - packages/domain
    - packages/string
dev_dependencies:
    build_runner: ^2.5.5
    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    flutter_lints: ^6.0.0
    flutter_test: { sdk: flutter }
    freezed: ^3.0.0
    test: ^1.26.3