name: artistic
description: app package
publish_to: none
resolution: workspace
version: 1.0.0+1

environment:
    sdk: ">=3.6.0 <5.0.0"

dependencies:
    collection: any
    cupertino_icons: ^1.0.8
    domain:
    flutter: { sdk: flutter }
    freezed_annotation: any
    logging: any
    meta: any
    riverpod: ^3.0.3
# dev_dependencies:
