name: string
description: app package
environment:
    sdk: '>=3.6.0 <5.0.0'
publish_to: none
resolution: workspace
version: 1.0.0+1

dependencies:
    collection: any
    domain:
    flutter: { sdk: flutter }
    flutter_localizations: { sdk: flutter }
    freezed_annotation: any
    intl: any
    logging: any
    meta: any
    safe_change_notifier: any
dev_dependencies:
    build_runner: any
    flutter_lints: ^6.0.0
    flutter_test: { sdk: flutter }
flutter:
    generate: true
