name: domain
description: domain package
publish_to: none
resolution: workspace
version: 1.0.0+1

environment:
    sdk: '>=3.6.0 <5.0.0'

dependencies:
    collection: any
    file_picker: any
    flutter: { sdk: flutter }
    freezed_annotation: any
    logging: any
    meta: any
    riverpod: ^3.0.3
    shared_preferences: any
    xml: any
dev_dependencies:
    freezed: any